branches:
  only:
  - master
  - development
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
python:
- "2.7_with_system_site_packages"
- 3.4
install:
  - pip install -r requirements.txt
  - pip install https://github.com/datamade/parseratorvariable/zipball/blocking
  - pip install -e .
script:
  - pytest tests --cov dedupe
after_success:
  - pip install coveralls
  - coveralls
sudo : off
