branches:
  only:
  - master
  - development
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
python:
- 2.7
- 3.4
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest tests --cov=dedupe
after_success:
- pip install coveralls
- coveralls
sudo: false
deploy:
  provider: pypi
  user: datamade.wheelbuilder
  password:
    secure: e/MuFPusrKfNP77vD9k4UDeG9BEkYFIi7kQOcaFbIJYyR7JkYctzgTqvbnf7xHLSfNray+QdgNdPBm/Rd4801yPQKuPD7NYY0LHC52zvoXC6bdwUMvN6WwJTBzMG/IVN2cpxOKREB6N36QC57WwCwSyHMUyUivgRRvq+I3BUxq8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dedupeio/dedupe-variable-name
